// AUTHENTICATE TYPES
export const AUTH_LOGIN_USER = 'AUTH_LOGIN_USER';
export const AUTH_LOGIN_USER_FAIL = 'AUTH_LOGIN_USER_FAIL';
export const AUTH_LOGIN_USER_SUCCESS = 'AUTH_LOGIN_USER_SUCCESS';
export const AUTH_CREATE_USER = 'AUTH_CREATE_USER';
export const AUTH_CREATE_USER_FAIL = 'AUTH_CREATE_USER_FAIL';
export const AUTH_CREATE_USER_SUCCESS = 'AUTH_CREATE_USER_SUCCESS';
export const AUTH_LOGOUT_USER = 'AUTH_LOGOUT_USER';
export const RESET_ERRORS = 'RESET_ERRORS';

// PROFILE TYPES
export const PROFILE_FETCH = 'PROFILE_FETCH';
export const PROFILE_UPDATE_GOALS = 'PROFILE_UPDATE_GOALS';

// GOALS TYPES
export const GOALS_FETCH = 'GOALS_FETCH';
